# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: menu.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmenu.proto\"E\n\x08MenuItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x02\"-\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x18\n\x05items\x18\x02 \x03(\x0b\x32\t.MenuItem\"#\n\tOrderList\x12\x16\n\x06orders\x18\x01 \x03(\x0b\x32\x06.Order\"\x15\n\x07OrderId\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xb6\x01\n\x0cOrderService\x12\x1c\n\x08\x41\x64\x64Order\x12\x06.Order\x1a\x06.Order\"\x00\x12$\n\x0cGetAllOrders\x12\x06.Empty\x1a\n.OrderList\"\x00\x12\x1e\n\x08GetOrder\x12\x08.OrderId\x1a\x06.Order\"\x00\x12\x1f\n\x0bUpdateOrder\x12\x06.Order\x1a\x06.Order\"\x00\x12!\n\x0b\x44\x65leteOrder\x12\x08.OrderId\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'menu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MENUITEM']._serialized_start=14
  _globals['_MENUITEM']._serialized_end=83
  _globals['_ORDER']._serialized_start=85
  _globals['_ORDER']._serialized_end=130
  _globals['_ORDERLIST']._serialized_start=132
  _globals['_ORDERLIST']._serialized_end=167
  _globals['_ORDERID']._serialized_start=169
  _globals['_ORDERID']._serialized_end=190
  _globals['_EMPTY']._serialized_start=192
  _globals['_EMPTY']._serialized_end=199
  _globals['_ORDERSERVICE']._serialized_start=202
  _globals['_ORDERSERVICE']._serialized_end=384
# @@protoc_insertion_point(module_scope)
